### ISSUE TITLE
VLAN Map

### ISSUE THREAD

**Issue by demmya** [cisco-config-analysis-tool/ccat#16]
Hi

Just tying to use your tool. Unclear with the VLAN Map
In the JSON  File
1) Are the numbers in the array the VLAN ID? if not  how do i generate one  for my config?
2)  Are the  Elements (e.g  DMZ, Management, Other) in you sample VLAN map defined in other scripts or can i create my own segments E.g  Office, internal , Guest  and put the corresponding VLAN id in the array

**Comment by AetherEternity** [comment]
Docs for vlanmap file are available here: https://github.com/frostbits-security/ccat/wiki/Vlanmap-file
So:
1. Yes, they are VLAN IDs
2. Nope
